# This workflow will do:
# - a clean installation of node dependencies, cache/restore them,
# - build the CV template
# - deploy Github Pages
#
# For more information see:
# - https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# - https://github.com/JamesIves/github-pages-deploy-action

name: Build CV Template and deploy to Github Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   # strategy:
  #   #   matrix:
  #   #     node-version: [16.x]
  #   #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.x
  #         cache: "npm"
  #     - run: npm install
  #     - run: npm run build
  #     # - run: npm run build --if-present
  #     # - run: npm test
  #     - name: Archive production artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: GithubPages
  #         path: dist

  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      # - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'dist' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      #   run: |
      #     npm install
      #     npm run build

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - run: npm run build

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
